volumes:
  xmltvdata:
  config:
  cache:

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - config:/config
      - cache:/cache
      - /mnt/torrent-lv:/media
      - xmltvdata:/xmltvdata
    environment:
    - PUID=1000
    - PGID=1000
    restart: "unless-stopped"
#    ports:
#      - 8096:8096
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    labels:
      # Enable Traefik for this router
      - "traefik.enable=true"
      # Traefik
      - "traefik.http.routers.jellyfin.entrypoints=http,https"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.zerodavid.net`)"
      - "traefik.http.routers.jellyfin.middlewares=https-redirectscheme@file,default-headers@file"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - zap2xml


  zap2xml:
    image: shuaiscott/zap2xml:latest
    restart: "unless-stopped"
    volumes:
      - xmltvdata:/data
    environment:
      - USERNAME=[redacted]
      - PASSWORD=[redacted]
      - OPT_ARGS=-I -D
      - XMLTV_FILENAME=channels.xml
    networks:
      - zap2xml

networks:
  proxy:
    external: true
  zap2xml:

